export { Home } from "./Home/Home"
export { Cart } from "./Cart/Cart"
export { Products } from "./Products"
export { ProductDetail } from "./ProductDetail"
export { Login } from "./Login"
export { Register } from "./Register"
export { PageNotFound } from "./PageNotFound"